### PR TITLE
added support for <titlelist regexp> to search page titles only

### PR DESCRIPTION
**Pull request by greenfive**
see: https://oddmuse.org/wiki/Search_List_Extension

The current implementation of the "Search List Extension" allows generate a "**ul**" based list on a search within page titles and pages bodies by using "**list regexp**".

This change adds a new tag "titlelist regexp" to only search within page titles. The generated "**ul**" list items contain a different CSS class (_titlelist_), so the generated list can be styled differently from a search based on page titles and page bodies.

### CODE REVIEW

**Comment by AlexDaniel** [comment]
Oh. OK, I'm starting to remember. I needed exactly this thing some time ago. And I actually added it to core because it was just a tiny modification to the journal syntax. See [Journal Pages](https://oddmuse.org/wiki/Journal_Pages).

So you are not very far off with your patch. I guess it can be used like this:
```
<titles 10 "REGEX">
```

Generally, you just change ``journal`` to ``titles`` and it should work.

Can you try it and see if it is good enough? If not, we can probably make some minor modifications.

**Comment by greenfive** [comment]
Thank you for your feedback, Alex!

The reasons I made the change to the "Search List Extension" are:

* The "Journal Extension" with the "titles" syntax wraps the search results in a new "div" with "class=journal", which makes sense if it is used in the journal environment or related to journal entries, like blog sites. However if one wants to use the "Journal Extension" for blogging, but including plain "search results" not related to blogging or journal entries, it makes things more complicated to tell them apart.

* The "Journal Extension" wraps each single result into an "h1" container. I don't exactly like having more than one "h1" on a page. As Oddmuse uses rather standard, pre-HTML5 generated HTML code, I prefer sticking with having only one "h1" container per page.

* The "Journal Extension" doesn't wrap the search results into "li" list items. One could code around that and style the divs with leading bullet points and indents, however then you would have the same design with journal entries and no way to differentiate both.

* The "Search List Extension" on the other hand already defines the new action and using parameters on the URL one can already ask for matches in the title or patterns in the content, or both. Only the Text Formatting Syntax lacks the support to match only on titles.
The results are already formatted as "ul" environments, containing the search results as "li" list items. The encompassing container is already a distinct "div" with more or less unique classes, to tell them apart from other divs, which makes designing them rather easy.

_Suggestions:_

* Add a Text Formatting Rule (like for example the "titlelist" syntax I suggested) to match the options for the added action

_Ideas for further enhancements:_

* Let the user decide whether he wants the results as an unordered "ul" list or an ordered "ol" list. This however would make a Text Formatting Rule syntax change necessary and not be backwards compatible, as far as I assume.

* Let the user limit the number of results returned. This however would make a Text Formatting Rule syntax change necessary and not be backwards compatible, as far as I assume.

* Let the user pick a limited number of random results matching the search, like e.g. "list 25 rand funnystuff" to list at most 25 entries matching "funnystuff", but random with each reload.

If you like when can discuss these ideas on IRC.

Cheers
Greenfive

**Comment by AlexDaniel** [comment]
Ah right, oops, it searches the content, not filters by title (that is, not what ``<titles …>`` syntax does)… that's a bit different indeed. Somehow I missed it.

**Comment by AlexDaniel** [comment]
Regarding the code, it seems to be an exact copy of the stuff above (with some minor modifications). Any chance to have it merged?

**Comment by AlexDaniel** [comment]
For example, ``<titles>`` and ``<journal>`` share the [same code path](https://github.com/kensanata/oddmuse/blob/master/wiki.pl#L469-L476), and the difference is just in this ``if``: https://github.com/kensanata/oddmuse/blob/4e0b287890b5800968750a132c4ac56c4c8e2754/wiki.pl#L879

**Pull request merged**
